### ISSUE TITLE
30 天精通 Git 版本控-學習進度安排

### ISSUE THREAD

**Issue by JiajunChou** [vincentliu104/Learning-Together#10]
# [30 天精通 Git 版本控管](https://github.com/doggy8088/Learn-Git-in-30-days/blob/master/zh-tw/README.md)

- [x] 第 01 天：認識 Git 版本控管
- [x] 第 02 天：在 Windows 平台必裝的三套 Git 工具
- [x] 第 03 天：建立儲存庫
- [x] 第 04 天：常用的 Git 版本控管指令
- [x] 第 05 天：了解儲存庫、工作目錄、物件與索引之間的關係
- [x] 第 06 天：解析 Git 資料結構 - 物件結構
- [x] 第 07 天：解析 Git 資料結構 - 索引結構
- [x] 第 08 天：關於分支的基本觀念與使用方式
- [x] 第 09 天：比對檔案與版本差異
- [x] 第 10 天：認識 Git 物件的絕對名稱
- [x] 第 11 天：認識 Git 物件的一般參照與符號參照
- [x] 第 12 天：認識 Git 物件的相對名稱
- [x] 第 13 天：暫存工作目錄與索引的變更狀態
- [x] 第 14 天：Git for Windows 選項設定
- [x] 第 15 天：標籤 - 標記版本控制過程中的重要事件
- [x] 第 16 天：善用版本日誌 git reflog 追蹤變更軌跡
- [x] 第 17 天：關於合併的基本觀念與使用方式
- [x] 第 18 天：修正 commit 過的版本歷史紀錄 Part 1 (reset & amend)
- [x] 第 19 天：設定 .gitignore 忽略清單
- [x] 第 20 天：修正 commit 過的版本歷史紀錄 Part 2 (revert)
- [x] 第 21 天：修正 commit 過的版本歷史紀錄 Part 3 (cherry-pick)
- [x] 第 22 天：修正 commit 過的版本歷史紀錄 Part 4 (rebase)
- [x] 第 23 天：修正 commit 過的版本歷史紀錄 Part 5 (rebase 2)
- [x] 第 24 天：使用 GitHub 遠端儲存庫 - 入門篇
- [x] 第 25 天：使用 GitHub 遠端儲存庫 - 觀念篇
- [x] 第 26 天：多人在同一個遠端儲存庫中進行版控
- [x] 第 27 天：透過分支在同一個遠端儲存庫中進行版控
- [x] 第 28 天：了解 GitHub 上 forks 與 pull request 的版控流程
- [x] 第 29 天：如何將 Subversion 專案匯入到 Git 儲存庫
- [x] 第 30 天：分享工作中幾個好用的 Git 操作技巧

**Comment by vincentliu99999** [comment]
- 可自行開 repo 練習(EX: `learning-git`)
- 新增檔案紀錄筆記：`Learning-Together/resources/Git/30 天精通 Git 版本控-學習進度安排.md`

**Comment by vincentliu104** [comment]
task list 全勾後發PR
