### ISSUE TITLE
VSCode 開發運用

### ISSUE THREAD

**Issue by vincentliu104** [vincentliu104/Learning-Together#14]
# VSCode

- [ ] snippet 使用教學

## 套件(Extension)

- [ ] [coldfusion by Ilya Verbitskiy 功能介紹](https://marketplace.visualstudio.com/items?itemName=ilich8086.ColdFusion)
- [ ] [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) 
- [ ] [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager): 讓你快速切換專案
- [ ] [File Utils](https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils): 用鍵盤操作檔案
- [ ] [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)
- [ ] [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)
- [ ] [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)

## 設定檔

- [Will 保哥的 VSCode 使用者設定檔 ](https://gist.github.com/doggy8088/6539a140f28924d3a1f053a8d3a9f49e)

**Comment by vincentliu99999** [comment]
@JiajunChou 

- snippet 使用教學

@chunghongke 

- coldfusion by Ilya Verbitskiy 功能介紹

**Comment by vincentliu99999** [comment]
@JiajunChou  調整建議如 comment 3dedba1f9fbeb7dcf92b152c9e7e166a45d7d74e

**Comment by vincentliu99999** [comment]
[Regex Railroad Diagram](https://marketplace.visualstudio.com/items?itemName=kogai.regex-railroad-diagrams): 正規表達式視覺化
