### ISSUE TITLE
攻城獅的學習資源整理

### ISSUE THREAD

**Issue by vincentliu104** [vincentliu104/Learning-Together#20]
有建議的資源歡迎留言

## 書籍

- [Programming Notes for Professionals books](https://books.goalkicker.com/)

## 線上課程

- [HiSKIO 跨領域學程式](https://hiskio.com/)
- [慕课网](https://www.imooc.com/course/list)

**Comment by dalice157** [comment]
[慕课网](https://www.imooc.com/course/list)

**Comment by vincentliu99999** [comment]
- [前端設計檢核清單](https://frontenddesignchecklist.io/)
- [前端效能檢核清單 ](https://github.com/thedaviddias/Front-End-Performance-Checklist)
