### ISSUE TITLE
好像把本地的Repo搞爆了

### ISSUE THREAD

**Issue by chunghongke** [vincentliu104/Learning-Together#24]
原本想用指令把寫在自己Repo的筆記移到learning-Together底下，但檔案被我更名成 `f:`
![](https://i.imgur.com/MiKBdBa.png)

後來還是用資料夾的方式直接剪下貼上移動

兩邊的Repo commit push完之後，發現VSCode有偵測到我刪除筆記檔案的變更，打開自己練習Repo的資料夾，發現 `f:`這個檔案還在，於是...
`rm -rf f:`
![](https://i.imgur.com/eqUa1oY.png)

然後我的資料夾就變以下這樣(原本的 learning-Together整個消失，只剩下自己練習的兩個Repo，但是裡面空空如也....)
![](https://i.imgur.com/ZcNuARp.png)

然後....Git指令完全不行!!
![](https://i.imgur.com/RmD4swC.png)

![](https://i.imgur.com/qhC6Xgb.png)

到Windows查我的git bash....
![](https://i.imgur.com/KzLBZja.png)

#### 囧RZ...

想請問大大發生什麼事情...

**Comment by vincentliu99999** [comment]
@chunghongke  連資料夾都不見，只能重來了

BTW, git 移動的指令是 `git mv <source> <destination>`

做錯要復原可以 `git reset --soft`

往後要移動檔案建議先用 File Explorer or IDE

**Comment by chunghongke** [comment]
Git整個重裝就好了，重新clone一份下來XD

**Comment by vincentliu99999** [comment]
如果要用指令，記得都要使用 git 來操作

沒問題就把 issue close 吧
