### ISSUE TITLE
開發工具收集

### ISSUE THREAD

**Issue by vincentliu104** [vincentliu104/Learning-Together#25]
- [Will 保哥的開發人員工具軟體清單 ( 最新 2017 年版 )](https://blog.miniasp.com/post/2017/09/13/Will-2017-Ultimate-Developer-Tool-Software-List.aspx)
- [tree-cli](https://github.com/MrRaindrop/tree-cli)
- [tldr](https://www.npmjs.com/package/tldr)
- [cloc](https://www.npmjs.com/package/cloc)
- [doctoc](https://www.npmjs.com/package/doctoc)

## tree-cli

```shell
npm install -g tree-cli
tree
tree -l 2 # max display depth = 2
tree -a # list all file
tree -f # '/' for directories

npm install -g doctoc
doctoc .
```

**Comment by vincentliu104** [comment]
跟 VSCode 有關先收集到 #14

**Comment by vincentliu99999** [comment]
- [LazyGit](https://github.com/jesseduffield/lazygit) Terminal 模式下可以用 “類“ GUI 的方式進行操作
