### ISSUE TITLE
Terminal 樣式 教學

### ISSUE THREAD

**Issue by dalice157** [vincentliu104/Learning-Together#28]
[導入、安裝、使用教學](https://medium.com/@chuanjen.wang/mac%E9%85%B7%E7%82%ABterminal-%E6%A8%A3%E5%BC%8F-%E9%A1%AF%E7%A4%BAgit-%E5%88%86%E6%94%AF-712cfb02b327)
- [x] 安裝 iTerm2
- [x] 安裝 zsh
- [x] 安裝oh-my-zsh
- [x] 變更樣式

**Comment by vincentliu99999** [comment]
#30 下次請用 `da/terminal`

**Comment by vincentliu99999** [comment]
[Style your Terminal better by mastering these settings 🤩 ](https://dev.to/sarthology/style-your-terminal-better-by-mastering-these-settings--4mie)
