### ISSUE TITLE
What Every Web Developer Should Know About HTTP

### ISSUE THREAD

**Issue by vincentliu99999** [vincentliu104/Learning-Together#39]
- [x] chapter 1: Resources
- [x] chapter 2: Messages
- [x] chapter 3: Connections
- [x] chapter 4: Web Architecture
- [x] chapter 5: State and Security

[What Every Web Developer Should Know About HTTP](https://www.amazon.com/Every-Developer-Should-OdeToCode-Programming-ebook/dp/B0076Z6VMI)

**Comment by vincentliu99999** [comment]
@chunghongke @JiajunChou @dalice157 @wenchien213 [我的筆記](https://github.com/vincentliu104/Learning-Together/tree/vincent/http/resources/HTTP) 歡迎來參閱，有問題可以直接發問

**Comment by wenchien213** [comment]
https://http.cat/            圖像版
