### ISSUE TITLE
CFML Tag to Script Conversions

### ISSUE THREAD

**Issue by JiajunChou** [vincentliu104/Learning-Together#43]
# [CFML Tag to Script Conversions](https://github.com/tonyjunkes/cfml-tags-to-cfscript/blob/master/README.md)

### 1./2./3. Start

1. [ ] The Modern Implementation of Tags to Script
1. [ ] Comments
1. [ ] Variables

### 4. Operators

1. [ ] Decision
1. [ ] Increment / Decrement
1. [ ] Inline Assignment
1. [ ] Boolean
1. [ ] Ternary & Null-Coalescing

### 5. Conditions

1. [ ] cfif / cfelseif / cfelse
1. [ ] cfswitch
1. [ ] cftry / cfcatch / cffinally
1. [ ] cfthrow & cfrethrow

### 6. Iterations

1. [ ] General Purpose Loop
1. [ ] Array Loop
1. [ ] Struct Loop
1. [ ] List Loop
1. [ ] Query Loop

### 7. Other Flow Control Tags

1. [ ] cfabort & cfexit

### 8. General

1. [ ] cfoutput
1. [ ] cfsavecontent
1. [ ] cfthread
1. [ ] cflock
1. [ ] cfinclude
1. [ ] cflocation

### 9. Debugging

1. [ ] cfdump
1. [ ] cflog

### 10. Database

1. [ ] cfquery
1. [ ] cftransaction

### 11. File System Operations

1. [ ] cfdirectory
1. [ ] cffile

### 12. Image Manipulation

1. [ ] cfimage

### 13. Spreadsheet Integration

1. [ ] cfspreadsheet

### 14. Tags Implemented as Components

1. [ ] cfquery / query.cfc
1. [ ] cfhttp / http.cfc
1. [ ] cfmail / mail.cfc
1. [ ] cffeed / feed.cfc
1. [ ] cfftp / ftp.cfc

### 15. Interfaces, Components & Functions

1. [ ] cfinterface
1. [ ] cfcomponent
1. [ ] cffunction
1. [ ] A More Complete Component Example
1. [ ] Annotations
1. [ ] Function Expressions

### 16. Real World Conversions By Example

1. [ ] Example 1
1. [ ] Example 2
1. [ ] Example 3

### 17. Tags Have Their Place

1. [ ] Keeping Tags in the View
1. [ ] Building Tag Code on the Script Side

**Comment by vincentliu104** [comment]
可以先略過的內容

- cflock
- cfexit
- cflog
- cfdirectory
- cfimage 
- cfspreadsheet
-  cfmail / mail.cfc
-   cffeed / feed.cfc
-   cfftp / ftp.cfc
